config/routes.rb
# Author: Sam
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :inquiries
  resources :houses
  resources :real_estate_companies

  root 'static_pages#index'

  # Static pages show
  get '/', to: 'static_pages#index'
  get '/index', to: 'static_pages#index'

  # User CRUD operations
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#edit'
  put '/user/:id', to: 'users#update'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'


  # Session CD operations
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/home', to: 'static_pages#home'

  # Real Estate CRUD operations
  get '/addcompany', to: 'real_estate_companies#new'
  post '/addcompany', to: 'real_estate_companies#create'
  get '/companies', to: 'real_estate_companies#show'
  get '/company/:id', to: 'real_estate_companies#edit'
  put '/company/:id', to: 'real_estate_companies#update'
  patch '/company/:id', to: 'real_estate_companies#update'
  delete '/company/:id', to: 'real_estate_companies#destroy'

  get '/choose', to: 'users#choose'
  post '/choose', to: 'users#update'
  put '/choose', to: 'users#update'
  patch '/choose', to: 'users#update'

  # House CRUD operations
  get '/listhouse', to: 'houses#new'
  post '/listhouse', to: 'houses#create'
  get '/houses', to: 'houses#show'
  get '/house/:id', to: 'houses#edit'
  put '/house/:id', to: 'houses#update'
  patch '/house/:id', to: 'houses#update'
  delete '/house/:id', to: 'houses#destroy'

  # Inquiry CRUD operations
  #get '/addinquiry/:id', to: 'inquiries#new'
  #post '/addinquiry/:id', to: 'inquiries#create'
  #get '/inquiries', to: 'inquiries#show'
  #get '/inquiry/:id', to: 'inquiries#edit'
  #put '/inquiry/:id', to: 'inquiries#update'
  #patch '/inquiry/:id', to: 'inquiries#update'
  #delete '/inquiry/:id', to: 'inquiries#destroy'

end

app/controllers/static_pages_controller.rb
# Author: Sam
class StaticPagesController < ApplicationController
  def index

  end
  def home
    @user = User.find_by(id: session[:user_id])
    @user = User.find_by(id: session[:user_id])
    if @user.nil?
      redirect_to root_path
    else
      @real_estate_company = RealEstateCompany.find_by(id: @user.company_id)
    end
  end
end

app/views/static_pages/home.html.erb
<!-- Author: Sam and Abhilasha -->
<div class="container" style="margin-top: 50px">
  <h1>Hey, <%= User.find_by(id: session[:user_id]).name %></h1>
  <h3>We are here to help people find their dream home :)</h3>
  <h6>How can we help you?</h6><br><br>
  <div class="row">
    <div class="container-fluid">
      <div class="card ">
        <div class="card-body">
          <h5 class="card-title">Edit or View your profile</h5>
          <p class="card-text">Change your information to correctly reflect who you are.</p>
          <%= link_to "Edit Your Profile", edit_user_path(@user) %><br/>
          <%= link_to "View Your Profile", @user %><br />
        </div>
      </div>
      <br />
      <div class="card ">
        <div class="card-body">
          <h5 class="card-title">Log Out</h5>
          <p class="card-text">Close your current session with the Real Estate Manager.</p>
          <%= link_to "Log Out", '/logout' %><br/>
        </div>
      </div>
      <br />

      <% if @user.roles == 0 %>
      <div class="card ">
        <!-- if admin -->
        <div class="card-body">
          <h5 class="card-title">View all users of the system</h5>
          <p class="card-text">See who uses this site.</p>
          <%= link_to "View All Users", users_path %><br/>
        </div>
      </div>
        <br />
      <% end %>

      <% if @user.roles == 0 %>
      <div class="card ">
        <!-- if admin -->
        <div class="card-body">
          <h5 class="card-title">Create a new user</h5>
          <p class="card-text">Create a new users for the Real Estate Manager.</p>
          <%= link_to "Create A User", new_user_path%><br/>
        </div>
      </div>
        <br />
      <% end %>

      <% if @user.roles != 1 %>
      <div class="card ">
        <!-- if house hunter -->
        <div class="card-body">
          <h5 class="card-title">Search available houses</h5>
          <p class="card-text">Look for your dream house according to your preferences.</p>
          <%= link_to "Browse Houses", houses_path %><br/>
        </div>
      </div>
      <br>
        <% end %>

      <% if @user.roles != 1 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Information about Real Estate Companies</h5>
          <p class="card-text">Know your company before you make a choice.</p>
          <%= link_to "View Real Estate Company Information", real_estate_companies_path %><br/>
        </div>
      </div>
      <br>
        <% end %>

      <% if @user.roles != 1 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">View Your Inquires</h5>
          <p class="card-text">Lists all your inquiries.</p>
          <%= link_to "View Your Inquiries", inquiries_path if @user.roles != 1 %><br/>
        </div>
      </div>
      <br>
        <% end %>

      <% if @user.roles != 2 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">List A House</h5>
          <p class="card-text">Add details of new house available here!</p>
          <%= link_to "List House", new_house_path %><br/>
        </div>
      </div>
      <br>
        <% end %>

        <% if @user.roles != 2 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">View Inquiries on Your Company's Houses</h5>
          <p class="card-text">List of Inquiries on Your Company's Houses.</p>
          <%= link_to "View Inquiries on Your Company's Houses", inquiries_path %><br/>
        </div>
      </div>
      <br>
          <% end %>

      <% if @user.roles != 2 && @real_estate_company %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Edit Your Company Information</h5>
          <p class="card-text">Update Your Company Information here!</p>
          <%= link_to "Edit Your Company Information", edit_real_estate_company_path(@real_estate_company) %><br/>
        </div>
      </div>
      <br>
      <% end %>

      <% if @user.roles != 2 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Select Your Real Estate Company</h5>
          <p class="card-text">Choose which Real Estate Company you are a part of, or create a new one!</p>
          <%= link_to "Select Real Estate Company", '/choose' %><br/>
        </div>
      </div>
      <br>
      <% end %>

      <% if @user.roles != 2 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">View All Listed Houses</h5>
          <p class="card-text">View All Listed Houses here!</p>
          <%= link_to "View All Listed Houses", houses_path %><br/>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<!-- Author: Abhilasha -->
<div class="container" style="align-content: center">
  <div class="wrapper">
    <div class="main">
      <div class="content">
        <div class="content_pages view">
          <div class="main-page" style="margin-top:80px;">
            <p style="font-size: 60px;text-align: center">Welcome!</p>
            <br>
            <%= link_to '<button type="button" class="btn btn-outline-secondary btn-block">SIGN IN</button>'.html_safe, new_session_url %>
            <br>
            <%= link_to '<button type="button" class="btn btn-outline-secondary btn-block">SIGN UP</button>'.html_safe, new_user_url %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>