config/routes.rb
# Author: Sam
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :inquiries
  resources :houses
  resources :real_estate_companies

  root 'static_pages#index'

  # Static pages show
  get '/', to: 'static_pages#index'
  get '/index', to: 'static_pages#index'

  # User CRUD operations
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#edit'
  put '/user/:id', to: 'users#update'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'


  # Session CD operations
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/home', to: 'static_pages#home'

  # Real Estate CRUD operations
  get '/addcompany', to: 'real_estate_companies#new'
  post '/addcompany', to: 'real_estate_companies#create'
  get '/companies', to: 'real_estate_companies#show'
  get '/company/:id', to: 'real_estate_companies#edit'
  put '/company/:id', to: 'real_estate_companies#update'
  patch '/company/:id', to: 'real_estate_companies#update'
  delete '/company/:id', to: 'real_estate_companies#destroy'

  get '/choose', to: 'users#choose'
  post '/choose', to: 'users#update'
  put '/choose', to: 'users#update'
  patch '/choose', to: 'users#update'

  # House CRUD operations
  get '/listhouse', to: 'houses#new'
  post '/listhouse', to: 'houses#create'
  get '/houses', to: 'houses#show'
  get '/house/:id', to: 'houses#edit'
  put '/house/:id', to: 'houses#update'
  patch '/house/:id', to: 'houses#update'
  delete '/house/:id', to: 'houses#destroy'

  # Inquiry CRUD operations
  #get '/addinquiry/:id', to: 'inquiries#new'
  #post '/addinquiry/:id', to: 'inquiries#create'
  #get '/inquiries', to: 'inquiries#show'
  #get '/inquiry/:id', to: 'inquiries#edit'
  #put '/inquiry/:id', to: 'inquiries#update'
  #patch '/inquiry/:id', to: 'inquiries#update'
  #delete '/inquiry/:id', to: 'inquiries#destroy'

end

app/controllers/houses_controller.rb
# Author: Sam and Abhilasha
class HousesController < ApplicationController
  def house_params
    params.require(:house).permit(:location, :square_footage, :year, :style, :price, :floors, :basement, :owner, :company_id)
  end

  def new
    @house = House.new
    @user = User.find(session[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @house }
    end
  end

  def create
    @user = User.find(session[:user_id])
    if @user.roles != 2 && !@user.company_id.nil?
      @house = House.new(house_params)
      @house.company_id = @user.company_id
      respond_to do |format|
        if @house.save
          format.html { redirect_to @house, notice: 'House was successfully listed.' }
          format.json { render json: @house, status: :created, location: @house }
        else
          format.html { render action: "new" }
          format.json { render json: @house.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def edit
    @house = House.find(params[:id])
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    @house = House.find(params[:id])
    if @user.roles != 2 && @user.id == @house.realtor_id

      respond_to do |format|
        if @house.update_attributes(house_params)
          format.html { redirect_to @house, notice: 'House was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @house.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def index
    @user = User.find(session[:user_id])
    @houses = House.all
    if params[:search]
      @search_term=params[:search]
      @houses=@houses.search_by(@search_term)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @houses }
    end
  end

  def show
    @house = House.find(params[:id])
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @house }
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    @house = House.find(params[:id])
    if @user.roles != 2 && @user.company_id == @house.company_id
      @house.destroy

      respond_to do |format|
        format.html { redirect_to houses_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<!-- Author: Sam -->
<%= form_for @house do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :square_footage %><br />
    <%= f.number_field :square_footage, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= f.label :style %><br />
    <%= f.select :style, [['Single Family House'], ['Apartment'], ['Condo']] %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :floors %><br />
    <%= f.number_field :floors %>
  </div>

  <div class="field">
    <%= f.label :basement %><br />
    <%= f.check_box :basement %>
  </div>

  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<!-- Author: Sam -->
<h1>Editing House Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<!-- Author: Abhilasha and Sam -->
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Houses</h1>
  <p>List of all the houses available.</p><br>
  <%= form_for "", url: houses_path, role: "search", method: :get do %>
    <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
  <% end %>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Located At</th>
      <th>Price</th>
      <th>Square Footage</th>
      <th>Floors</th>
      <th>Basement</th>
      <th>Style</th>
      <th>House owner</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.price %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.style %></td>
        <td><%= house.owner %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) if @user.roles != 2 && @user.company_id == house.company_id %></td>
        <td><%= button_to 'Remove Listing',  house, method: :delete, data: {confirm: 'Are you sure?'} if @user.roles != 2 && @user.company_id == house.company_id%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>


<br>

<%= link_to 'List a House', new_house_url if @user.roles != 2 %>
<%= link_to 'Home', home_path %>

app/views/houses/new.html.erb
<!-- Author: Sam -->
<h1>List A House</h1>

<%= render 'form' %>

<%= link_to 'Back', home_path %>

app/views/houses/show.html.erb
<!-- Author: Sam -->
<p id="notice"><%= notice %></p>
<p>
  <b>Location:</b>
  <%= @house.location %>
</p>

<p>
  <b>Square Footage:</b>
  <%= @house.square_footage %>
</p>

<p>
  <b>Year Built:</b>
  <%= @house.year %>
</p>

<p>
  <b>Style:</b>
  <%= @house.style %>
</p>

<p>
  <b>List Price:</b>
  <%= @house.price %>
</p>

<p>
  <b>Number of Floors:</b>
  <%= @house.floors %>
</p>

<p>
  <b>Has Basement:</b>
  <%= @house.basement %>
</p>

<%= link_to 'Edit', edit_house_path(@house) if @user.roles != 2 && @user.company_id == @house.company_id %> |
<%= link_to 'Inquire about this House', new_inquiry_path(@house) if @user.roles != 1%> |
<%= link_to 'Back', houses_path %>