config/routes.rb
# Author: Sam
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :inquiries
  resources :houses
  resources :real_estate_companies

  root 'static_pages#index'

  # Static pages show
  get '/', to: 'static_pages#index'
  get '/index', to: 'static_pages#index'

  # User CRUD operations
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#edit'
  put '/user/:id', to: 'users#update'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'


  # Session CD operations
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/home', to: 'static_pages#home'

  # Real Estate CRUD operations
  get '/addcompany', to: 'real_estate_companies#new'
  post '/addcompany', to: 'real_estate_companies#create'
  get '/companies', to: 'real_estate_companies#show'
  get '/company/:id', to: 'real_estate_companies#edit'
  put '/company/:id', to: 'real_estate_companies#update'
  patch '/company/:id', to: 'real_estate_companies#update'
  delete '/company/:id', to: 'real_estate_companies#destroy'

  get '/choose', to: 'users#choose'
  post '/choose', to: 'users#update'
  put '/choose', to: 'users#update'
  patch '/choose', to: 'users#update'

  # House CRUD operations
  get '/listhouse', to: 'houses#new'
  post '/listhouse', to: 'houses#create'
  get '/houses', to: 'houses#show'
  get '/house/:id', to: 'houses#edit'
  put '/house/:id', to: 'houses#update'
  patch '/house/:id', to: 'houses#update'
  delete '/house/:id', to: 'houses#destroy'

  # Inquiry CRUD operations
  #get '/addinquiry/:id', to: 'inquiries#new'
  #post '/addinquiry/:id', to: 'inquiries#create'
  #get '/inquiries', to: 'inquiries#show'
  #get '/inquiry/:id', to: 'inquiries#edit'
  #put '/inquiry/:id', to: 'inquiries#update'
  #patch '/inquiry/:id', to: 'inquiries#update'
  #delete '/inquiry/:id', to: 'inquiries#destroy'

end

app/models/user.rb
# Author: Sam
class User < ApplicationRecord
  has_secure_password

  validates :name, :presence => true
  #can put additional validation here
  validates :email, :presence => true,
            :uniqueness => true
  validates :roles, :presence => true
end

app/controllers/users_controller.rb
# Author: Sam
class UsersController < ApplicationController
  def user_params
    params.require(:user).permit(:name, :email, :password, :roles, :company_id, :phone_number, :preferred_contact_method)
  end

  def index
    if User.find(session[:user_id]).roles == 0
      @users = User.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
    end
  end

  def show
    if params[:id].to_s == session[:user_id].to_s || User.find(session[:user_id]).roles == 0
      @user = User.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
          format.html { redirect_to home_path, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    if params[:id].to_s == session[:user_id].to_s || User.find(session[:user_id]).roles == 0
      @user = User.find(params[:id])
    else
      redirect_to home_path
    end
  end

  def choose
    @real_estate_companies = RealEstateCompany.all
    @user = User.find(session[:user_id])
  end

  def update
    if params[:id].to_s == session[:user_id].to_s || User.find(session[:user_id]).roles == 0
      @user = User.find(params[:id])

      respond_to do |format|
        if @user.update_attributes(user_params)
          format.html { redirect_to '/home', notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to home_path
    end
  end

  def destroy
    @logged_in = User.find(session[:user_id])
    if @logged_in.id == params[:id] || @logged_in.roles == 0
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    end
  end
end

app/views/users/_form.html.erb
<!-- Author: Sam -->
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <% if @user && @user.roles != 0 %>
  <div class="field">
    <%= f.label :roles %><br />
    <%= f.select :roles, [['I am a realtor', 1], ['I am shopping for a house', 2],
                                 ['I am a realtor and I am shopping for a house', 3]] %>
  </div>
    <% end %>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :preferred_contact_method %><br />
    <%= f.select :preferred_contact_method, ['Text', 'Phone Call', 'Email'] %>
  </div><br />

  <div class="actions">
    <%= f.submit %>
  </div><br />
<% end %>

app/views/users/choose.html.erb
<!-- Author: Sam -->
<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :company_id %><br />
    <% options= options_from_collection_for_select(@real_estate_companies, 'id', 'name')%>
    <%= f.select :company_id, options, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Create a New Real Estate Company', new_real_estate_company_path %>

app/views/users/edit.html.erb
<!-- Author: Sam -->
<h1>Editing Your Profile</h1>
<div class="container" style="margin-top: 50px">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Edit Profile</h2>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', home_path %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- Author: Sam -->
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Houses</h1>
  <p>List of all the houses available.</p><br>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>User ID</th>
      <th>Name</th>
      <th>Roles</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Preferred Contact Method</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.roles %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.preferred_contact_method %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user)%></td>
        <td><%= button_to 'Remove',  user, method: :delete, data: {confirm: 'Are you sure?'} if user.roles != 0%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>


<br>

<%= link_to "Add a User", new_user_url %>|
<%= link_to "Back", home_path %>

app/views/users/new.html.erb
<!-- Author: Sam -->
<h1>Create Your Account</h1>
<div class="container" style="margin-top: 50px">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Sign Up</h2>
<%= render 'form' %>
      <%= link_to 'Back', root_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- Author: Sam -->
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Roles:</b>
  <!-- remember to turn these into strings-->
  <%= @user.roles%>
</p>

<%= @user.company_id %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', home_path %>