config/routes.rb
# Author: Sam
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :inquiries
  resources :houses
  resources :real_estate_companies

  root 'static_pages#index'

  # Static pages show
  get '/', to: 'static_pages#index'
  get '/index', to: 'static_pages#index'

  # User CRUD operations
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  get '/user/:id', to: 'users#edit'
  put '/user/:id', to: 'users#update'
  patch '/user/:id', to: 'users#update'
  delete '/user/:id', to: 'users#destroy'


  # Session CD operations
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/home', to: 'static_pages#home'

  # Real Estate CRUD operations
  get '/addcompany', to: 'real_estate_companies#new'
  post '/addcompany', to: 'real_estate_companies#create'
  get '/companies', to: 'real_estate_companies#show'
  get '/company/:id', to: 'real_estate_companies#edit'
  put '/company/:id', to: 'real_estate_companies#update'
  patch '/company/:id', to: 'real_estate_companies#update'
  delete '/company/:id', to: 'real_estate_companies#destroy'

  get '/choose', to: 'users#choose'
  post '/choose', to: 'users#update'
  put '/choose', to: 'users#update'
  patch '/choose', to: 'users#update'

  # House CRUD operations
  get '/listhouse', to: 'houses#new'
  post '/listhouse', to: 'houses#create'
  get '/houses', to: 'houses#show'
  get '/house/:id', to: 'houses#edit'
  put '/house/:id', to: 'houses#update'
  patch '/house/:id', to: 'houses#update'
  delete '/house/:id', to: 'houses#destroy'

  # Inquiry CRUD operations
  #get '/addinquiry/:id', to: 'inquiries#new'
  #post '/addinquiry/:id', to: 'inquiries#create'
  #get '/inquiries', to: 'inquiries#show'
  #get '/inquiry/:id', to: 'inquiries#edit'
  #put '/inquiry/:id', to: 'inquiries#update'
  #patch '/inquiry/:id', to: 'inquiries#update'
  #delete '/inquiry/:id', to: 'inquiries#destroy'

end

app/models/inquiry.rb
# Author: Ameya
class Inquiry < ApplicationRecord
  belongs_to :house
  #belongs_to :real_estate_company
  belongs_to :user

  validates :subject, :presence => true
  validates :message, :presence => true
end

app/controllers/inquiries_controller.rb
# Author: Ameya
class InquiriesController < ApplicationController
  def inquiry_params
    params.require(:inquiry).permit(:subject, :message)
  end
  def new
    @inquiry = Inquiry.new(inquiry_params)
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find(session[:user_id])
    if @user.roles != 1
      @inquiry = Inquiry.new(inquiry_params)
      respond_to do |format|
        if @inquiry.save
          format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
          format.json { render json: @inquiry, status: :created, location: @inquiry }
        else
          format.html { render action: "new" }
          format.json { render json: @inquiry.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def edit
    @inquiry = Inquiry.find(params[:id])
    @user = User.find(session[:user_id])
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    @user = User.find(session[:user_id])
    respond_to do |format|
      if @inquiry.update_attributes(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @inquiry = Inquiry.find(params[:id])
    @user = User.find(session[:user_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inquiry }
    end
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])
    @user = User.find(session[:user_id])
    @inquiry.destroy

    respond_to do |format|
      format.html { redirect_to inquiries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<!-- Author: Sam -->
<%= form_for @inquiry do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% @inquiry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<!-- Author: Ameya -->
<div class="container" style="margin-top: 50px">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Editing Inquiry Information</h2>
      <br>
      <%= render 'form' %>

      <%= link_to 'Show', @house %> |
      <%= link_to 'Back', houses_path %>
    </div>
  </div>
</div>

app/views/inquiries/index.html.erb
<!-- Author: Ameya -->

<%= link_to "Create an inquiry", new_inquiry_url %>

app/views/inquiries/new.html.erb
<!-- Author: Ameya -->
<div class="container" style="margin-top: 50px">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Create a new inquiry</h2>
      <br>
      <%= render 'form' %>
      <br>
      <%= link_to 'Back', inquiries_path %>
    </div>
  </div>
</div>

app/views/inquiries/show.html.erb
<!-- Author: Ameya -->
<div class="container" style="margin-left: 10px">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Location:</b>
    <%= @house.location %>
  </p>

  <p>
    <strong>House owner:</strong>
    <%= @house.owner %>
  </p>

  <p>
    <b>List Price:</b>
    <%= @house.price %>
  </p>

  <p>
    <b>Year Built:</b>
    <%= @house.year %>
  </p>

  <p>
    <b>Number of Floors:</b>
    <%= @house.floors %>
  </p>

  <p>
    <b>Style:</b>
    <%= @house.style %>
  </p>

  <p>
    <b>Basement:</b>
    <%= @house.basement %>
  </p>


  <p>
    <b>Square Footage:</b>
    <%= @house.square_footage %>
  </p>

  <!-- If posting realtor -->
  <%= link_to 'Edit this inquiry', edit_inquiry_path %> |
  <!-- If house hunter -->
  <%= link_to 'Inquire about this House', new_inquiry_path %>

  <%= link_to 'List Houses', houses_path %>

</div>